### ISSUE TITLE
error after installing from extensions tab 

### ISSUE THREAD

**Issue by 3blackbar** [sebaxakerhtc/sd-webui-demofusion#10]
So it does not show up in webui, heres the error    

[-] ADetailer initialized. version: 23.11.0, num models: 15
ControlNet preprocessor location: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-04 02:17:46,306 - ControlNet - INFO - ControlNet v1.1.440
2024-04-04 02:17:49,422 - ControlNet - INFO - ControlNet v1.1.440
*** Error loading script: iface.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\stable-diffusion-webui\extensions\sd-webui-demofusion\scripts\iface.py", line 11, in <module>
        from demofusion.pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
      File "F:\stable-diffusion-webui\extensions\sd-webui-demofusion\demofusion\pipeline_demofusion_sdxl.py", line 28, in <module>
        from diffusers.loaders import (
    ImportError: cannot import name 'FromSingleFileMixin' from 'diffusers.loaders' (F:\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders.py)

---
Loading weights [4726d3bab1] from F:\stable-diffusion-webui\models\Stable-diffusion\dreamshaperXL_v2TurboDpmppSDE.safetensors
2024-04-04 02:18:04,099 - ControlNet - INFO - ControlNet UI callback registered.
[ui] Creating UI components
Creating model from config: F:\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7861

**Comment by sebaxakerhtc** [comment]
@3blackbar 
Hi and thank you for the issue!
I will try to reproduce it on a clean installation.

**Comment by sebaxakerhtc** [comment]
@3blackbar 
On clean installation of webui there's no errors. 
All works fine.

Can you please provide information about versions and installed extensions?

**Comment by sebaxakerhtc** [comment]
> im on webui 1.7

I think the problem is here.
I always use the latest version.

I'll try with 1.7

**Comment by sebaxakerhtc** [comment]
@3blackbar 
Installed successfully on a clean 1.7
Still cannot reproduce your issue

**Comment by 3blackbar** [comment]
I solved it by installing latest dev branch of auto11 , also theres a bug in demofusion when you will select a VAE, it tries to connect with huggingface for some reason and check password ? When i dont choose any vae it works fine 

    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-660e96df-0ef6f26d383599b03802e649;04f3955b-8271-4fa4-b1f7-eef5a1fc0f41)

Repository Not Found for url: https://huggingface.co/sdxl.vae.safetensors/resolve/main/.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

**Comment by sebaxakerhtc** [comment]
> Theres guidance scale missing in this extension

It's renamed as CFG Scale

> Another bug - when the main model you choose is not matching model chosen in demofusionn panel

It's not a BUG - it should work like this, because it uses original Diffusers, that's why we have a separated model loade

> The class CLIPFeatureExtractor is deprecated

Try using the latest version of webUI. Your errors is going from deprecated packages



> when you will select a VAE, it tries to connect with huggingface

Will test it

**Comment by sebaxakerhtc** [comment]
@3blackbar
BUG with VAE reproduced, thank you!

**Comment by w-e-w** [comment]
feel free to ping me if you need help

**Comment by sebaxakerhtc** [comment]
@w-e-w 
I looking at this
```
    found_model = sd_models.get_closet_checkpoint_match(selected_model)
    if found_model:
        model_ckpt = found_model.filename
```
but can't find the `get_closet_checkpoint_match` for vae

**Comment by w-e-w** [comment]
I don't call theres a it is a equivalent version of that function for vaes as there is only a handful of vae's

**Comment by w-e-w** [comment]
I thinks this is what you seed
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/b372fb6165c2b0f3990d9a3ff06245d25358c0b8/modules/sd_vae.py#L136

**Comment by sebaxakerhtc** [comment]
> I don't call theres a it is a equivalent version of that function for vaes as there is only a handful of vae's

It sends only filename instead of full path

**Comment by w-e-w** [comment]
heck, at this point I might as well do it for you

**Comment by w-e-w** [comment]
give me a 5 minutes to make

**Comment by sebaxakerhtc** [comment]
> give me a 5 minutes to make a PR

I'm sure you will do it better.
For now I did it like this `shared.cmd_opts.lora_dir + sd_lora_file` Ahhaha

**Comment by 3blackbar** [comment]
I just did 2048x2048 and for some reason it switched from gpu to cpu inference... weird and slow as hell, if ill be able to reproduce ill create new issue.

**Comment by sebaxakerhtc** [comment]
> it switched from gpu to cpu inference

Very strange...
It's hardcoded here
```
    pipe = pipe.to("cuda")
    generator = torch.Generator(device='cuda')
```

**Comment by sebaxakerhtc** [comment]
> So this kinda works like upscaler , magnific or similar, but changes the image too much, is it possible to set denoise amount ? I dont see denoise slider like in img2img

Read about cosines and use additional parameters for it



> Where are results saved and why not in txt2img or img2img folders ?

This is the main problem I work on.

**Comment by 3blackbar** [comment]
in demo guidance scale starts from 0 , here it starts from 1.1 , can you change it so it allows for any value from 0 as well ?

**Comment by sebaxakerhtc** [comment]
> in demo guidance scale starts from 0 , here it starts from 1.1 , can you change it so it allows for any value from 0 as well ?

https://github.com/sebaxakerhtc/sd-webui-demofusion/commit/0dec309b80f5b903b85934e687e7fa157cf78f0b
Look here:
```
 CFG scale minimum to 1.1

Not sure about why, but setting to 1 we'll have error
```
